/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-IEs"
 * 	found in "../../src/sbcap/asn1/SBC_AP_IEs.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_TAI_5GS_H_
#define	_SBcAP_TAI_5GS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/sbcap/SBcAP_PLMNidentity.h>
#include <osmocom/sbcap/SBcAP_TAC-5GS.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SBcAP_ProtocolExtensionContainer;

/* SBcAP_TAI-5GS */
typedef struct SBcAP_TAI_5GS {
	SBcAP_PLMNidentity_t	 pLMNidentity;
	SBcAP_TAC_5GS_t	 tAC_5GS;
	struct SBcAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_TAI_5GS_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_TAI_5GS;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_TAI_5GS_specs_1;
extern asn_TYPE_member_t asn_MBR_SBcAP_TAI_5GS_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */

#endif	/* _SBcAP_TAI_5GS_H_ */
#include <asn_internal.h>
