/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-PDU-Contents"
 * 	found in "../../src/sbcap/asn1/SBC_AP_PDU_Contents.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_Error_Indication_H_
#define	_SBcAP_Error_Indication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/sbcap/SBcAP_ProtocolIE-Container.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SBcAP_Error-Indication */
typedef struct SBcAP_Error_Indication {
	SBcAP_ProtocolIE_Container_86P8_t	 protocolIEs;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Error_Indication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Error_Indication;

#ifdef __cplusplus
}
#endif

#endif	/* _SBcAP_Error_Indication_H_ */
#include <asn_internal.h>
