/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-IEs"
 * 	found in "../../src/sbcap/asn1/SBC_AP_IEs.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_Criticality_Diagnostics_H_
#define	_SBcAP_Criticality_Diagnostics_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/sbcap/SBcAP_ProcedureCode.h>
#include <osmocom/sbcap/SBcAP_TriggeringMessage.h>
#include <osmocom/sbcap/SBcAP_Criticality.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SBcAP_CriticalityDiagnostics_IE_List;
struct SBcAP_ProtocolExtensionContainer;

/* SBcAP_Criticality-Diagnostics */
typedef struct SBcAP_Criticality_Diagnostics {
	SBcAP_ProcedureCode_t	*procedureCode;	/* OPTIONAL */
	SBcAP_TriggeringMessage_t	*triggeringMessage;	/* OPTIONAL */
	SBcAP_Criticality_t	*procedureCriticality;	/* OPTIONAL */
	struct SBcAP_CriticalityDiagnostics_IE_List	*iE_CriticalityDiagnostics;	/* OPTIONAL */
	struct SBcAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Criticality_Diagnostics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Criticality_Diagnostics;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Criticality_Diagnostics_specs_1;
extern asn_TYPE_member_t asn_MBR_SBcAP_Criticality_Diagnostics_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <osmocom/sbcap/SBcAP_CriticalityDiagnostics-IE-List.h>
#include <osmocom/sbcap/SBcAP_ProtocolExtensionContainer.h>

#endif	/* _SBcAP_Criticality_Diagnostics_H_ */
#include <asn_internal.h>
