/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-CommonDataTypes"
 * 	found in "../../src/sbcap/asn1/SBC_AP_CommonDataTypes.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_TriggeringMessage_H_
#define	_SBcAP_TriggeringMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SBcAP_TriggeringMessage {
	SBcAP_TriggeringMessage_initiating_message	= 0,
	SBcAP_TriggeringMessage_successful_outcome	= 1,
	SBcAP_TriggeringMessage_unsuccessful_outcome	= 2,
	SBcAP_TriggeringMessage_outcome	= 3
} e_SBcAP_TriggeringMessage;

/* SBcAP_TriggeringMessage */
typedef long	 SBcAP_TriggeringMessage_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SBcAP_TriggeringMessage_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_TriggeringMessage;
extern const asn_INTEGER_specifics_t asn_SPC_SBcAP_TriggeringMessage_specs_1;
asn_struct_free_f SBcAP_TriggeringMessage_free;
asn_struct_print_f SBcAP_TriggeringMessage_print;
asn_constr_check_f SBcAP_TriggeringMessage_constraint;
per_type_decoder_f SBcAP_TriggeringMessage_decode_aper;
per_type_encoder_f SBcAP_TriggeringMessage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SBcAP_TriggeringMessage_H_ */
#include <asn_internal.h>
