/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-Containers"
 * 	found in "../../src/sbcap/asn1/SBC_AP_Containers.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_ProtocolIE_ContainerList_H_
#define	_SBcAP_ProtocolIE_ContainerList_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _SBcAP_ProtocolIE_ContainerList_H_ */
#include <asn_internal.h>
