/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-CommonDataTypes"
 * 	found in "../../src/sbcap/asn1/SBC_AP_CommonDataTypes.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_Presence_H_
#define	_SBcAP_Presence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SBcAP_Presence {
	SBcAP_Presence_optional	= 0,
	SBcAP_Presence_conditional	= 1,
	SBcAP_Presence_mandatory	= 2
} e_SBcAP_Presence;

/* SBcAP_Presence */
typedef long	 SBcAP_Presence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SBcAP_Presence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Presence;
extern const asn_INTEGER_specifics_t asn_SPC_Presence_specs_1;
asn_struct_free_f Presence_free;
asn_struct_print_f Presence_print;
asn_constr_check_f Presence_constraint;
per_type_decoder_f Presence_decode_aper;
per_type_encoder_f Presence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SBcAP_Presence_H_ */
#include <asn_internal.h>
