/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-IEs"
 * 	found in "../../src/sbcap/asn1/SBC_AP_IEs.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_Cause_H_
#define	_SBcAP_Cause_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SBcAP_Cause {
	SBcAP_Cause_message_accepted	= 0,
	SBcAP_Cause_parameter_not_recognised	= 1,
	SBcAP_Cause_parameter_value_invalid	= 2,
	SBcAP_Cause_valid_message_not_identified	= 3,
	SBcAP_Cause_tracking_area_not_valid	= 4,
	SBcAP_Cause_unrecognised_message	= 5,
	SBcAP_Cause_missing_mandatory_element	= 6,
	SBcAP_Cause_mME_capacity_exceeded	= 7,
	SBcAP_Cause_mME_memory_exceeded	= 8,
	SBcAP_Cause_warning_broadcast_not_supported	= 9,
	SBcAP_Cause_warning_broadcast_not_operational	= 10,
	SBcAP_Cause_message_reference_already_used	= 11,
	SBcAP_Cause_unspecifed_error	= 12,
	SBcAP_Cause_transfer_syntax_error	= 13,
	SBcAP_Cause_semantic_error	= 14,
	SBcAP_Cause_message_not_compatible_with_receiver_state	= 15,
	SBcAP_Cause_abstract_syntax_error_reject	= 16,
	SBcAP_Cause_abstract_syntax_error_ignore_and_notify	= 17,
	SBcAP_Cause_abstract_syntax_error_falsely_constructed_message	= 18
} e_SBcAP_Cause;

/* SBcAP_Cause */
typedef long	 SBcAP_Cause_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SBcAP_Cause_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Cause;
asn_struct_free_f SBcAP_Cause_free;
asn_struct_print_f SBcAP_Cause_print;
asn_constr_check_f SBcAP_Cause_constraint;
per_type_decoder_f SBcAP_Cause_decode_aper;
per_type_encoder_f SBcAP_Cause_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SBcAP_Cause_H_ */
#include <asn_internal.h>
