/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-IEs"
 * 	found in "../../src/sbcap/asn1/SBC_AP_IEs.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_Warning_Area_List_5GS_H_
#define	_SBcAP_Warning_Area_List_5GS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/sbcap/SBcAP_ECGIList.h>
#include <osmocom/sbcap/SBcAP_NR-CGIList.h>
#include <osmocom/sbcap/SBcAP_TAI-5GS.h>
#include <osmocom/sbcap/SBcAP_Emergency-Area-ID-List.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SBcAP_Warning_Area_List_5GS_PR {
	SBcAP_Warning_Area_List_5GS_PR_NOTHING,	/* No components present */
	SBcAP_Warning_Area_List_5GS_PR_cell_ID_List,
	SBcAP_Warning_Area_List_5GS_PR_nR_CGIList,
	SBcAP_Warning_Area_List_5GS_PR_tAIList_5GS,
	SBcAP_Warning_Area_List_5GS_PR_emergencyAreaIDList
	/* Extensions may appear below */
	
} SBcAP_Warning_Area_List_5GS_PR;

/* SBcAP_Warning-Area-List-5GS */
typedef struct SBcAP_Warning_Area_List_5GS {
	SBcAP_Warning_Area_List_5GS_PR present;
	union SBcAP_Warning_Area_List_5GS_u {
		SBcAP_ECGIList_t	 cell_ID_List;
		SBcAP_NR_CGIList_t	 nR_CGIList;
		SBcAP_TAI_5GS_t	 tAIList_5GS;
		SBcAP_Emergency_Area_ID_List_t	 emergencyAreaIDList;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Warning_Area_List_5GS_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Warning_Area_List_5GS;
extern asn_CHOICE_specifics_t asn_SPC_SBcAP_Warning_Area_List_5GS_specs_1;
extern asn_TYPE_member_t asn_MBR_SBcAP_Warning_Area_List_5GS_1[4];
extern asn_per_constraints_t asn_PER_type_SBcAP_Warning_Area_List_5GS_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SBcAP_Warning_Area_List_5GS_H_ */
#include <asn_internal.h>
