/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-Containers"
 * 	found in "../../src/sbcap/asn1/SBC_AP_Containers.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_ProtocolExtensionField_H_
#define	_SBcAP_ProtocolExtensionField_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/sbcap/SBcAP_ProtocolExtensionID.h>
#include <osmocom/sbcap/SBcAP_Criticality.h>
#include <ANY.h>
#include <asn_ioc.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include <osmocom/sbcap/SBcAP_List-of-5GS-TAIs.h>
#include <osmocom/sbcap/SBcAP_Presence.h>
#include <osmocom/sbcap/SBcAP_Warning-Area-List-5GS.h>
#include <osmocom/sbcap/SBcAP_Global-RAN-Node-ID.h>
#include <osmocom/sbcap/SBcAP_RAT-Selector-5GS.h>
#include <osmocom/sbcap/SBcAP_Unknown-5GS-Tracking-Area-List.h>
#include <osmocom/sbcap/SBcAP_Broadcast-Scheduled-Area-List-5GS.h>
#include <osmocom/sbcap/SBcAP_Broadcast-Cancelled-Area-List-5GS.h>
#include <osmocom/sbcap/SBcAP_Broadcast-Empty-Area-List-5GS.h>
#include <osmocom/sbcap/SBcAP_Restarted-Cell-List-NR.h>
#include <osmocom/sbcap/SBcAP_List-of-5GS-TAI-for-Restart.h>
#include <osmocom/sbcap/SBcAP_Global-GNB-ID.h>
#include <osmocom/sbcap/SBcAP_Failed-Cell-List-NR.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SBcAP_Broadcast_Scheduled_Area_List_ExtIEs__extensionValue_PR {
	SBcAP_Broadcast_Scheduled_Area_List_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_Broadcast_Scheduled_Area_List_ExtIEs__extensionValue_PR;
typedef enum SBcAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs__extensionValue_PR {
	SBcAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs__extensionValue_PR;
typedef enum SBcAP_Broadcast_Cancelled_Area_List_ExtIEs__extensionValue_PR {
	SBcAP_Broadcast_Cancelled_Area_List_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_Broadcast_Cancelled_Area_List_ExtIEs__extensionValue_PR;
typedef enum SBcAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs__extensionValue_PR {
	SBcAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs__extensionValue_PR;
typedef enum SBcAP_CancelledCellinEAI_Item_ExtIEs__extensionValue_PR {
	SBcAP_CancelledCellinEAI_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_CancelledCellinEAI_Item_ExtIEs__extensionValue_PR;
typedef enum SBcAP_CancelledCellinTAI_Item_ExtIEs__extensionValue_PR {
	SBcAP_CancelledCellinTAI_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_CancelledCellinTAI_Item_ExtIEs__extensionValue_PR;
typedef enum SBcAP_CancelledCellinTAI_5GS_ExtIEs__extensionValue_PR {
	SBcAP_CancelledCellinTAI_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_CancelledCellinTAI_5GS_ExtIEs__extensionValue_PR;
typedef enum SBcAP_CellId_Broadcast_List_Item_ExtIEs__extensionValue_PR {
	SBcAP_CellId_Broadcast_List_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_CellId_Broadcast_List_Item_ExtIEs__extensionValue_PR;
typedef enum SBcAP_CellId_Broadcast_List_5GS_ExtIEs__extensionValue_PR {
	SBcAP_CellId_Broadcast_List_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_CellId_Broadcast_List_5GS_ExtIEs__extensionValue_PR;
typedef enum SBcAP_CellID_Cancelled_Item_ExtIEs__extensionValue_PR {
	SBcAP_CellID_Cancelled_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_CellID_Cancelled_Item_ExtIEs__extensionValue_PR;
typedef enum SBcAP_CellID_Cancelled_5GS_ExtIEs__extensionValue_PR {
	SBcAP_CellID_Cancelled_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_CellID_Cancelled_5GS_ExtIEs__extensionValue_PR;
typedef enum SBcAP_CriticalityDiagnostics_ExtIEs__extensionValue_PR {
	SBcAP_CriticalityDiagnostics_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_CriticalityDiagnostics_ExtIEs__extensionValue_PR;
typedef enum SBcAP_CriticalityDiagnostics_IE_Item_ExtIEs__extensionValue_PR {
	SBcAP_CriticalityDiagnostics_IE_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_CriticalityDiagnostics_IE_Item_ExtIEs__extensionValue_PR;
typedef enum SBcAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs__extensionValue_PR {
	SBcAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs__extensionValue_PR;
typedef enum SBcAP_EmergencyAreaID_Cancelled_Item_ExtIEs__extensionValue_PR {
	SBcAP_EmergencyAreaID_Cancelled_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_EmergencyAreaID_Cancelled_Item_ExtIEs__extensionValue_PR;
typedef enum SBcAP_EUTRAN_CGI_ExtIEs__extensionValue_PR {
	SBcAP_EUTRAN_CGI_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_EUTRAN_CGI_ExtIEs__extensionValue_PR;
typedef enum SBcAP_GlobalENB_ID_ExtIEs__extensionValue_PR {
	SBcAP_GlobalENB_ID_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_GlobalENB_ID_ExtIEs__extensionValue_PR;
typedef enum SBcAP_Global_GNB_ID_ExtIEs__extensionValue_PR {
	SBcAP_Global_GNB_ID_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_Global_GNB_ID_ExtIEs__extensionValue_PR;
typedef enum SBcAP_Global_NgENB_ID_ExtIEs__extensionValue_PR {
	SBcAP_Global_NgENB_ID_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_Global_NgENB_ID_ExtIEs__extensionValue_PR;
typedef enum SBcAP_NR_CGI_ExtIEs__extensionValue_PR {
	SBcAP_NR_CGI_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_NR_CGI_ExtIEs__extensionValue_PR;
typedef enum SBcAP_ScheduledCellinEAI_Item_ExtIEs__extensionValue_PR {
	SBcAP_ScheduledCellinEAI_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_ScheduledCellinEAI_Item_ExtIEs__extensionValue_PR;
typedef enum SBcAP_ScheduledCellinTAI_Item_ExtIEs__extensionValue_PR {
	SBcAP_ScheduledCellinTAI_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_ScheduledCellinTAI_Item_ExtIEs__extensionValue_PR;
typedef enum SBcAP_ScheduledCellinTAI_5GS_ExtIEs__extensionValue_PR {
	SBcAP_ScheduledCellinTAI_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_ScheduledCellinTAI_5GS_ExtIEs__extensionValue_PR;
typedef enum SBcAP_TAI_Broadcast_List_Item_ExtIEs__extensionValue_PR {
	SBcAP_TAI_Broadcast_List_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_TAI_Broadcast_List_Item_ExtIEs__extensionValue_PR;
typedef enum SBcAP_TAI_Broadcast_List_5GS_ExtIEs__extensionValue_PR {
	SBcAP_TAI_Broadcast_List_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_TAI_Broadcast_List_5GS_ExtIEs__extensionValue_PR;
typedef enum SBcAP_TAI_Cancelled_List_Item_ExtIEs__extensionValue_PR {
	SBcAP_TAI_Cancelled_List_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_TAI_Cancelled_List_Item_ExtIEs__extensionValue_PR;
typedef enum SBcAP_TAI_Cancelled_List_5GS_ExtIEs__extensionValue_PR {
	SBcAP_TAI_Cancelled_List_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_TAI_Cancelled_List_5GS_ExtIEs__extensionValue_PR;
typedef enum SBcAP_TAI_ExtIEs__extensionValue_PR {
	SBcAP_TAI_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_TAI_ExtIEs__extensionValue_PR;
typedef enum SBcAP_TAI_5GS_ExtIEs__extensionValue_PR {
	SBcAP_TAI_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBcAP_TAI_5GS_ExtIEs__extensionValue_PR;
typedef enum SBcAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR {
	SBcAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBcAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR_List_of_5GS_TAIs,
	SBcAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR_Warning_Area_List_5GS,
	SBcAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR_Global_RAN_Node_ID,
	SBcAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR_RAT_Selector_5GS
} SBcAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR;
typedef enum SBcAP_Write_Replace_Warning_Response_Extensions__extensionValue_PR {
	SBcAP_Write_Replace_Warning_Response_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBcAP_Write_Replace_Warning_Response_Extensions__extensionValue_PR_Unknown_5GS_Tracking_Area_List
} SBcAP_Write_Replace_Warning_Response_Extensions__extensionValue_PR;
typedef enum SBcAP_Stop_Warning_Request_Extensions__extensionValue_PR {
	SBcAP_Stop_Warning_Request_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBcAP_Stop_Warning_Request_Extensions__extensionValue_PR_List_of_5GS_TAIs,
	SBcAP_Stop_Warning_Request_Extensions__extensionValue_PR_Warning_Area_List_5GS,
	SBcAP_Stop_Warning_Request_Extensions__extensionValue_PR_RAT_Selector_5GS
} SBcAP_Stop_Warning_Request_Extensions__extensionValue_PR;
typedef enum SBcAP_Stop_Warning_Response_Extensions__extensionValue_PR {
	SBcAP_Stop_Warning_Response_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBcAP_Stop_Warning_Response_Extensions__extensionValue_PR_Unknown_5GS_Tracking_Area_List
} SBcAP_Stop_Warning_Response_Extensions__extensionValue_PR;
typedef enum SBcAP_Write_Replace_Warning_Indication_Extensions__extensionValue_PR {
	SBcAP_Write_Replace_Warning_Indication_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBcAP_Write_Replace_Warning_Indication_Extensions__extensionValue_PR_Broadcast_Scheduled_Area_List_5GS
} SBcAP_Write_Replace_Warning_Indication_Extensions__extensionValue_PR;
typedef enum SBcAP_Stop_Warning_Indication_Extensions__extensionValue_PR {
	SBcAP_Stop_Warning_Indication_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBcAP_Stop_Warning_Indication_Extensions__extensionValue_PR_Broadcast_Cancelled_Area_List_5GS,
	SBcAP_Stop_Warning_Indication_Extensions__extensionValue_PR_Broadcast_Empty_Area_List_5GS
} SBcAP_Stop_Warning_Indication_Extensions__extensionValue_PR;
typedef enum SBcAP_PWS_Restart_Indication_Extensions__extensionValue_PR {
	SBcAP_PWS_Restart_Indication_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBcAP_PWS_Restart_Indication_Extensions__extensionValue_PR_Restarted_Cell_List_NR,
	SBcAP_PWS_Restart_Indication_Extensions__extensionValue_PR_List_of_5GS_TAI_for_Restart,
	SBcAP_PWS_Restart_Indication_Extensions__extensionValue_PR_Global_GNB_ID
} SBcAP_PWS_Restart_Indication_Extensions__extensionValue_PR;
typedef enum SBcAP_PWS_Failure_Indication_Extensions__extensionValue_PR {
	SBcAP_PWS_Failure_Indication_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBcAP_PWS_Failure_Indication_Extensions__extensionValue_PR_Failed_Cell_List_NR,
	SBcAP_PWS_Failure_Indication_Extensions__extensionValue_PR_Global_GNB_ID
} SBcAP_PWS_Failure_Indication_Extensions__extensionValue_PR;

/* SBcAP_ProtocolExtensionField */
typedef struct SBcAP_Broadcast_Scheduled_Area_List_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_Broadcast_Scheduled_Area_List_ExtIEs__extensionValue {
		SBcAP_Broadcast_Scheduled_Area_List_ExtIEs__extensionValue_PR present;
		union SBcAP_Broadcast_Scheduled_Area_List_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Broadcast_Scheduled_Area_List_ExtIEs_t;
typedef struct SBcAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs__extensionValue {
		SBcAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs__extensionValue_PR present;
		union SBcAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs_t;
typedef struct SBcAP_Broadcast_Cancelled_Area_List_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_Broadcast_Cancelled_Area_List_ExtIEs__extensionValue {
		SBcAP_Broadcast_Cancelled_Area_List_ExtIEs__extensionValue_PR present;
		union SBcAP_Broadcast_Cancelled_Area_List_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Broadcast_Cancelled_Area_List_ExtIEs_t;
typedef struct SBcAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs__extensionValue {
		SBcAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs__extensionValue_PR present;
		union SBcAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs_t;
typedef struct SBcAP_CancelledCellinEAI_Item_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_CancelledCellinEAI_Item_ExtIEs__extensionValue {
		SBcAP_CancelledCellinEAI_Item_ExtIEs__extensionValue_PR present;
		union SBcAP_CancelledCellinEAI_Item_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_CancelledCellinEAI_Item_ExtIEs_t;
typedef struct SBcAP_CancelledCellinTAI_Item_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_CancelledCellinTAI_Item_ExtIEs__extensionValue {
		SBcAP_CancelledCellinTAI_Item_ExtIEs__extensionValue_PR present;
		union SBcAP_CancelledCellinTAI_Item_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_CancelledCellinTAI_Item_ExtIEs_t;
typedef struct SBcAP_CancelledCellinTAI_5GS_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_CancelledCellinTAI_5GS_ExtIEs__extensionValue {
		SBcAP_CancelledCellinTAI_5GS_ExtIEs__extensionValue_PR present;
		union SBcAP_CancelledCellinTAI_5GS_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_CancelledCellinTAI_5GS_ExtIEs_t;
typedef struct SBcAP_CellId_Broadcast_List_Item_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_CellId_Broadcast_List_Item_ExtIEs__extensionValue {
		SBcAP_CellId_Broadcast_List_Item_ExtIEs__extensionValue_PR present;
		union SBcAP_CellId_Broadcast_List_Item_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_CellId_Broadcast_List_Item_ExtIEs_t;
typedef struct SBcAP_CellId_Broadcast_List_5GS_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_CellId_Broadcast_List_5GS_ExtIEs__extensionValue {
		SBcAP_CellId_Broadcast_List_5GS_ExtIEs__extensionValue_PR present;
		union SBcAP_CellId_Broadcast_List_5GS_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_CellId_Broadcast_List_5GS_ExtIEs_t;
typedef struct SBcAP_CellID_Cancelled_Item_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_CellID_Cancelled_Item_ExtIEs__extensionValue {
		SBcAP_CellID_Cancelled_Item_ExtIEs__extensionValue_PR present;
		union SBcAP_CellID_Cancelled_Item_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_CellID_Cancelled_Item_ExtIEs_t;
typedef struct SBcAP_CellID_Cancelled_5GS_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_CellID_Cancelled_5GS_ExtIEs__extensionValue {
		SBcAP_CellID_Cancelled_5GS_ExtIEs__extensionValue_PR present;
		union SBcAP_CellID_Cancelled_5GS_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_CellID_Cancelled_5GS_ExtIEs_t;
typedef struct SBcAP_CriticalityDiagnostics_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_CriticalityDiagnostics_ExtIEs__extensionValue {
		SBcAP_CriticalityDiagnostics_ExtIEs__extensionValue_PR present;
		union SBcAP_CriticalityDiagnostics_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_CriticalityDiagnostics_ExtIEs_t;
typedef struct SBcAP_CriticalityDiagnostics_IE_Item_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_CriticalityDiagnostics_IE_Item_ExtIEs__extensionValue {
		SBcAP_CriticalityDiagnostics_IE_Item_ExtIEs__extensionValue_PR present;
		union SBcAP_CriticalityDiagnostics_IE_Item_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_CriticalityDiagnostics_IE_Item_ExtIEs_t;
typedef struct SBcAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs__extensionValue {
		SBcAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs__extensionValue_PR present;
		union SBcAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs_t;
typedef struct SBcAP_EmergencyAreaID_Cancelled_Item_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_EmergencyAreaID_Cancelled_Item_ExtIEs__extensionValue {
		SBcAP_EmergencyAreaID_Cancelled_Item_ExtIEs__extensionValue_PR present;
		union SBcAP_EmergencyAreaID_Cancelled_Item_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_EmergencyAreaID_Cancelled_Item_ExtIEs_t;
typedef struct SBcAP_EUTRAN_CGI_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_EUTRAN_CGI_ExtIEs__extensionValue {
		SBcAP_EUTRAN_CGI_ExtIEs__extensionValue_PR present;
		union SBcAP_EUTRAN_CGI_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_EUTRAN_CGI_ExtIEs_t;
typedef struct SBcAP_GlobalENB_ID_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_GlobalENB_ID_ExtIEs__extensionValue {
		SBcAP_GlobalENB_ID_ExtIEs__extensionValue_PR present;
		union SBcAP_GlobalENB_ID_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_GlobalENB_ID_ExtIEs_t;
typedef struct SBcAP_Global_GNB_ID_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_Global_GNB_ID_ExtIEs__extensionValue {
		SBcAP_Global_GNB_ID_ExtIEs__extensionValue_PR present;
		union SBcAP_Global_GNB_ID_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Global_GNB_ID_ExtIEs_t;
typedef struct SBcAP_Global_NgENB_ID_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_Global_NgENB_ID_ExtIEs__extensionValue {
		SBcAP_Global_NgENB_ID_ExtIEs__extensionValue_PR present;
		union SBcAP_Global_NgENB_ID_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Global_NgENB_ID_ExtIEs_t;
typedef struct SBcAP_NR_CGI_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_NR_CGI_ExtIEs__extensionValue {
		SBcAP_NR_CGI_ExtIEs__extensionValue_PR present;
		union SBcAP_NR_CGI_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_NR_CGI_ExtIEs_t;
typedef struct SBcAP_ScheduledCellinEAI_Item_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_ScheduledCellinEAI_Item_ExtIEs__extensionValue {
		SBcAP_ScheduledCellinEAI_Item_ExtIEs__extensionValue_PR present;
		union SBcAP_ScheduledCellinEAI_Item_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_ScheduledCellinEAI_Item_ExtIEs_t;
typedef struct SBcAP_ScheduledCellinTAI_Item_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_ScheduledCellinTAI_Item_ExtIEs__extensionValue {
		SBcAP_ScheduledCellinTAI_Item_ExtIEs__extensionValue_PR present;
		union SBcAP_ScheduledCellinTAI_Item_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_ScheduledCellinTAI_Item_ExtIEs_t;
typedef struct SBcAP_ScheduledCellinTAI_5GS_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_ScheduledCellinTAI_5GS_ExtIEs__extensionValue {
		SBcAP_ScheduledCellinTAI_5GS_ExtIEs__extensionValue_PR present;
		union SBcAP_ScheduledCellinTAI_5GS_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_ScheduledCellinTAI_5GS_ExtIEs_t;
typedef struct SBcAP_TAI_Broadcast_List_Item_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_TAI_Broadcast_List_Item_ExtIEs__extensionValue {
		SBcAP_TAI_Broadcast_List_Item_ExtIEs__extensionValue_PR present;
		union SBcAP_TAI_Broadcast_List_Item_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_TAI_Broadcast_List_Item_ExtIEs_t;
typedef struct SBcAP_TAI_Broadcast_List_5GS_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_TAI_Broadcast_List_5GS_ExtIEs__extensionValue {
		SBcAP_TAI_Broadcast_List_5GS_ExtIEs__extensionValue_PR present;
		union SBcAP_TAI_Broadcast_List_5GS_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_TAI_Broadcast_List_5GS_ExtIEs_t;
typedef struct SBcAP_TAI_Cancelled_List_Item_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_TAI_Cancelled_List_Item_ExtIEs__extensionValue {
		SBcAP_TAI_Cancelled_List_Item_ExtIEs__extensionValue_PR present;
		union SBcAP_TAI_Cancelled_List_Item_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_TAI_Cancelled_List_Item_ExtIEs_t;
typedef struct SBcAP_TAI_Cancelled_List_5GS_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_TAI_Cancelled_List_5GS_ExtIEs__extensionValue {
		SBcAP_TAI_Cancelled_List_5GS_ExtIEs__extensionValue_PR present;
		union SBcAP_TAI_Cancelled_List_5GS_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_TAI_Cancelled_List_5GS_ExtIEs_t;
typedef struct SBcAP_TAI_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_TAI_ExtIEs__extensionValue {
		SBcAP_TAI_ExtIEs__extensionValue_PR present;
		union SBcAP_TAI_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_TAI_ExtIEs_t;
typedef struct SBcAP_TAI_5GS_ExtIEs {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_TAI_5GS_ExtIEs__extensionValue {
		SBcAP_TAI_5GS_ExtIEs__extensionValue_PR present;
		union SBcAP_TAI_5GS_ExtIEs__SBcAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_TAI_5GS_ExtIEs_t;
typedef struct SBcAP_Write_Replace_Warning_Request_Extensions {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_Write_Replace_Warning_Request_Extensions__extensionValue {
		SBcAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR present;
		union SBcAP_Write_Replace_Warning_Request_Extensions__SBcAP_extensionValue_u {
			SBcAP_List_of_5GS_TAIs_t	 List_of_5GS_TAIs;
			SBcAP_Warning_Area_List_5GS_t	 Warning_Area_List_5GS;
			SBcAP_Global_RAN_Node_ID_t	 Global_RAN_Node_ID;
			SBcAP_RAT_Selector_5GS_t	 RAT_Selector_5GS;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Write_Replace_Warning_Request_Extensions_t;
typedef struct SBcAP_Write_Replace_Warning_Response_Extensions {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_Write_Replace_Warning_Response_Extensions__extensionValue {
		SBcAP_Write_Replace_Warning_Response_Extensions__extensionValue_PR present;
		union SBcAP_Write_Replace_Warning_Response_Extensions__SBcAP_extensionValue_u {
			SBcAP_Unknown_5GS_Tracking_Area_List_t	 Unknown_5GS_Tracking_Area_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Write_Replace_Warning_Response_Extensions_t;
typedef struct SBcAP_Stop_Warning_Request_Extensions {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_Stop_Warning_Request_Extensions__extensionValue {
		SBcAP_Stop_Warning_Request_Extensions__extensionValue_PR present;
		union SBcAP_Stop_Warning_Request_Extensions__SBcAP_extensionValue_u {
			SBcAP_List_of_5GS_TAIs_t	 List_of_5GS_TAIs;
			SBcAP_Warning_Area_List_5GS_t	 Warning_Area_List_5GS;
			SBcAP_RAT_Selector_5GS_t	 RAT_Selector_5GS;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Stop_Warning_Request_Extensions_t;
typedef struct SBcAP_Stop_Warning_Response_Extensions {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_Stop_Warning_Response_Extensions__extensionValue {
		SBcAP_Stop_Warning_Response_Extensions__extensionValue_PR present;
		union SBcAP_Stop_Warning_Response_Extensions__SBcAP_extensionValue_u {
			SBcAP_Unknown_5GS_Tracking_Area_List_t	 Unknown_5GS_Tracking_Area_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Stop_Warning_Response_Extensions_t;
typedef struct SBcAP_Write_Replace_Warning_Indication_Extensions {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_Write_Replace_Warning_Indication_Extensions__extensionValue {
		SBcAP_Write_Replace_Warning_Indication_Extensions__extensionValue_PR present;
		union SBcAP_Write_Replace_Warning_Indication_Extensions__SBcAP_extensionValue_u {
			SBcAP_Broadcast_Scheduled_Area_List_5GS_t	 Broadcast_Scheduled_Area_List_5GS;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Write_Replace_Warning_Indication_Extensions_t;
typedef struct SBcAP_Stop_Warning_Indication_Extensions {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_Stop_Warning_Indication_Extensions__extensionValue {
		SBcAP_Stop_Warning_Indication_Extensions__extensionValue_PR present;
		union SBcAP_Stop_Warning_Indication_Extensions__SBcAP_extensionValue_u {
			SBcAP_Broadcast_Cancelled_Area_List_5GS_t	 Broadcast_Cancelled_Area_List_5GS;
			SBcAP_Broadcast_Empty_Area_List_5GS_t	 Broadcast_Empty_Area_List_5GS;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Stop_Warning_Indication_Extensions_t;
typedef struct SBcAP_PWS_Restart_Indication_Extensions {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_PWS_Restart_Indication_Extensions__extensionValue {
		SBcAP_PWS_Restart_Indication_Extensions__extensionValue_PR present;
		union SBcAP_PWS_Restart_Indication_Extensions__SBcAP_extensionValue_u {
			SBcAP_Restarted_Cell_List_NR_t	 Restarted_Cell_List_NR;
			SBcAP_List_of_5GS_TAI_for_Restart_t	 List_of_5GS_TAI_for_Restart;
			SBcAP_Global_GNB_ID_t	 Global_GNB_ID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_PWS_Restart_Indication_Extensions_t;
typedef struct SBcAP_PWS_Failure_Indication_Extensions {
	SBcAP_ProtocolExtensionID_t	 id;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_PWS_Failure_Indication_Extensions__extensionValue {
		SBcAP_PWS_Failure_Indication_Extensions__extensionValue_PR present;
		union SBcAP_PWS_Failure_Indication_Extensions__SBcAP_extensionValue_u {
			SBcAP_Failed_Cell_List_NR_t	 Failed_Cell_List_NR;
			SBcAP_Global_GNB_ID_t	 Global_GNB_ID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_PWS_Failure_Indication_Extensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Broadcast_Scheduled_Area_List_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Broadcast_Scheduled_Area_List_ExtIEs_specs_1;
extern asn_TYPE_member_t asn_MBR_SBcAP_Broadcast_Scheduled_Area_List_ExtIEs_1[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs_specs_5;
extern asn_TYPE_member_t asn_MBR_SBcAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs_5[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Broadcast_Cancelled_Area_List_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Broadcast_Cancelled_Area_List_ExtIEs_specs_9;
extern asn_TYPE_member_t asn_MBR_SBcAP_Broadcast_Cancelled_Area_List_ExtIEs_9[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs_specs_13;
extern asn_TYPE_member_t asn_MBR_SBcAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs_13[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_CancelledCellinEAI_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_CancelledCellinEAI_Item_ExtIEs_specs_17;
extern asn_TYPE_member_t asn_MBR_SBcAP_CancelledCellinEAI_Item_ExtIEs_17[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_CancelledCellinTAI_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_CancelledCellinTAI_Item_ExtIEs_specs_21;
extern asn_TYPE_member_t asn_MBR_SBcAP_CancelledCellinTAI_Item_ExtIEs_21[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_CancelledCellinTAI_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_CancelledCellinTAI_5GS_ExtIEs_specs_25;
extern asn_TYPE_member_t asn_MBR_SBcAP_CancelledCellinTAI_5GS_ExtIEs_25[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_CellId_Broadcast_List_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_CellId_Broadcast_List_Item_ExtIEs_specs_29;
extern asn_TYPE_member_t asn_MBR_SBcAP_CellId_Broadcast_List_Item_ExtIEs_29[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_CellId_Broadcast_List_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_CellId_Broadcast_List_5GS_ExtIEs_specs_33;
extern asn_TYPE_member_t asn_MBR_SBcAP_CellId_Broadcast_List_5GS_ExtIEs_33[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_CellID_Cancelled_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_CellID_Cancelled_Item_ExtIEs_specs_37;
extern asn_TYPE_member_t asn_MBR_SBcAP_CellID_Cancelled_Item_ExtIEs_37[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_CellID_Cancelled_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_CellID_Cancelled_5GS_ExtIEs_specs_41;
extern asn_TYPE_member_t asn_MBR_SBcAP_CellID_Cancelled_5GS_ExtIEs_41[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_CriticalityDiagnostics_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_CriticalityDiagnostics_ExtIEs_specs_45;
extern asn_TYPE_member_t asn_MBR_SBcAP_CriticalityDiagnostics_ExtIEs_45[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_CriticalityDiagnostics_IE_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_CriticalityDiagnostics_IE_Item_ExtIEs_specs_49;
extern asn_TYPE_member_t asn_MBR_SBcAP_CriticalityDiagnostics_IE_Item_ExtIEs_49[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs_specs_53;
extern asn_TYPE_member_t asn_MBR_SBcAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs_53[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_EmergencyAreaID_Cancelled_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_EmergencyAreaID_Cancelled_Item_ExtIEs_specs_57;
extern asn_TYPE_member_t asn_MBR_SBcAP_EmergencyAreaID_Cancelled_Item_ExtIEs_57[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_EUTRAN_CGI_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_EUTRAN_CGI_ExtIEs_specs_61;
extern asn_TYPE_member_t asn_MBR_SBcAP_EUTRAN_CGI_ExtIEs_61[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_GlobalENB_ID_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_GlobalENB_ID_ExtIEs_specs_65;
extern asn_TYPE_member_t asn_MBR_SBcAP_GlobalENB_ID_ExtIEs_65[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Global_GNB_ID_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Global_GNB_ID_ExtIEs_specs_69;
extern asn_TYPE_member_t asn_MBR_SBcAP_Global_GNB_ID_ExtIEs_69[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Global_NgENB_ID_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Global_NgENB_ID_ExtIEs_specs_73;
extern asn_TYPE_member_t asn_MBR_SBcAP_Global_NgENB_ID_ExtIEs_73[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_NR_CGI_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_NR_CGI_ExtIEs_specs_77;
extern asn_TYPE_member_t asn_MBR_SBcAP_NR_CGI_ExtIEs_77[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_ScheduledCellinEAI_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_ScheduledCellinEAI_Item_ExtIEs_specs_81;
extern asn_TYPE_member_t asn_MBR_SBcAP_ScheduledCellinEAI_Item_ExtIEs_81[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_ScheduledCellinTAI_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_ScheduledCellinTAI_Item_ExtIEs_specs_85;
extern asn_TYPE_member_t asn_MBR_SBcAP_ScheduledCellinTAI_Item_ExtIEs_85[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_ScheduledCellinTAI_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_ScheduledCellinTAI_5GS_ExtIEs_specs_89;
extern asn_TYPE_member_t asn_MBR_SBcAP_ScheduledCellinTAI_5GS_ExtIEs_89[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_TAI_Broadcast_List_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_TAI_Broadcast_List_Item_ExtIEs_specs_93;
extern asn_TYPE_member_t asn_MBR_SBcAP_TAI_Broadcast_List_Item_ExtIEs_93[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_TAI_Broadcast_List_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_TAI_Broadcast_List_5GS_ExtIEs_specs_97;
extern asn_TYPE_member_t asn_MBR_SBcAP_TAI_Broadcast_List_5GS_ExtIEs_97[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_TAI_Cancelled_List_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_TAI_Cancelled_List_Item_ExtIEs_specs_101;
extern asn_TYPE_member_t asn_MBR_SBcAP_TAI_Cancelled_List_Item_ExtIEs_101[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_TAI_Cancelled_List_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_TAI_Cancelled_List_5GS_ExtIEs_specs_105;
extern asn_TYPE_member_t asn_MBR_SBcAP_TAI_Cancelled_List_5GS_ExtIEs_105[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_TAI_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_TAI_ExtIEs_specs_109;
extern asn_TYPE_member_t asn_MBR_SBcAP_TAI_ExtIEs_109[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_TAI_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_TAI_5GS_ExtIEs_specs_113;
extern asn_TYPE_member_t asn_MBR_SBcAP_TAI_5GS_ExtIEs_113[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Write_Replace_Warning_Request_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Write_Replace_Warning_Request_Extensions_specs_117;
extern asn_TYPE_member_t asn_MBR_SBcAP_Write_Replace_Warning_Request_Extensions_117[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Write_Replace_Warning_Response_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Write_Replace_Warning_Response_Extensions_specs_121;
extern asn_TYPE_member_t asn_MBR_SBcAP_Write_Replace_Warning_Response_Extensions_121[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Stop_Warning_Request_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Stop_Warning_Request_Extensions_specs_125;
extern asn_TYPE_member_t asn_MBR_SBcAP_Stop_Warning_Request_Extensions_125[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Stop_Warning_Response_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Stop_Warning_Response_Extensions_specs_129;
extern asn_TYPE_member_t asn_MBR_SBcAP_Stop_Warning_Response_Extensions_129[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Write_Replace_Warning_Indication_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Write_Replace_Warning_Indication_Extensions_specs_133;
extern asn_TYPE_member_t asn_MBR_SBcAP_Write_Replace_Warning_Indication_Extensions_133[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Stop_Warning_Indication_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_Stop_Warning_Indication_Extensions_specs_137;
extern asn_TYPE_member_t asn_MBR_SBcAP_Stop_Warning_Indication_Extensions_137[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_PWS_Restart_Indication_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_PWS_Restart_Indication_Extensions_specs_141;
extern asn_TYPE_member_t asn_MBR_SBcAP_PWS_Restart_Indication_Extensions_141[3];
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_PWS_Failure_Indication_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_PWS_Failure_Indication_Extensions_specs_145;
extern asn_TYPE_member_t asn_MBR_SBcAP_PWS_Failure_Indication_Extensions_145[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SBcAP_ProtocolExtensionField_H_ */
#include <asn_internal.h>
