/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-IEs"
 * 	found in "../../src/sbcap/asn1/SBC_AP_IEs.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_CriticalityDiagnostics_IE_List_H_
#define	_SBcAP_CriticalityDiagnostics_IE_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <osmocom/sbcap/SBcAP_Criticality.h>
#include <osmocom/sbcap/SBcAP_ProtocolIE-ID.h>
#include <osmocom/sbcap/SBcAP_TypeOfError.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SBcAP_ProtocolExtensionContainer;

/* Forward definitions */
typedef struct SBcAP_CriticalityDiagnostics_IE_List__Member {
	SBcAP_Criticality_t	 iECriticality;
	SBcAP_ProtocolIE_ID_t	 iE_ID;
	SBcAP_TypeOfError_t	 typeOfError;
	struct SBcAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CriticalityDiagnostics_IE_List__Member;

/* SBcAP_CriticalityDiagnostics-IE-List */
typedef struct SBcAP_CriticalityDiagnostics_IE_List {
	A_SEQUENCE_OF(CriticalityDiagnostics_IE_List__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_CriticalityDiagnostics_IE_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_CriticalityDiagnostics_IE_List;
extern asn_SET_OF_specifics_t asn_SPC_SBcAP_CriticalityDiagnostics_IE_List_specs_1;
extern asn_TYPE_member_t asn_MBR_SBcAP_CriticalityDiagnostics_IE_List_1[1];
extern asn_per_constraints_t asn_PER_type_SBcAP_CriticalityDiagnostics_IE_List_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <osmocom/sbcap/SBcAP_ProtocolExtensionContainer.h>

#endif	/* _SBcAP_CriticalityDiagnostics_IE_List_H_ */
#include <asn_internal.h>
