/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-PDU-Descriptions"
 * 	found in "../../src/sbcap/asn1/SBC_AP_PDU_Descriptions.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_SuccessfulOutcome_H_
#define	_SBcAP_SuccessfulOutcome_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/sbcap/SBcAP_ProcedureCode.h>
#include <osmocom/sbcap/SBcAP_Criticality.h>
#include <ANY.h>
#include <asn_ioc.h>
#include <osmocom/sbcap/SBcAP_Write-Replace-Warning-Request.h>
#include <osmocom/sbcap/SBcAP_Write-Replace-Warning-Response.h>
#include <osmocom/sbcap/SBcAP_Stop-Warning-Request.h>
#include <osmocom/sbcap/SBcAP_Stop-Warning-Response.h>
#include <osmocom/sbcap/SBcAP_Error-Indication.h>
#include <osmocom/sbcap/SBcAP_Write-Replace-Warning-Indication.h>
#include <osmocom/sbcap/SBcAP_Stop-Warning-Indication.h>
#include <osmocom/sbcap/SBcAP_PWS-Restart-Indication.h>
#include <osmocom/sbcap/SBcAP_PWS-Failure-Indication.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SBcAP_SuccessfulOutcome__value_PR {
	SBcAP_SuccessfulOutcome__value_PR_NOTHING,	/* No components present */
	SBcAP_SuccessfulOutcome__value_PR_Write_Replace_Warning_Response,
	SBcAP_SuccessfulOutcome__value_PR_Stop_Warning_Response
} SBcAP_SuccessfulOutcome__value_PR;

/* SBcAP_SuccessfulOutcome */
typedef struct SBcAP_SuccessfulOutcome {
	SBcAP_ProcedureCode_t	 procedureCode;
	SBcAP_Criticality_t	 criticality;
	struct SBcAP_SuccessfulOutcome__value {
		SBcAP_SuccessfulOutcome__value_PR present;
		union SBcAP_SuccessfulOutcome__SBcAP_value_u {
			SBcAP_Write_Replace_Warning_Response_t	 Write_Replace_Warning_Response;
			SBcAP_Stop_Warning_Response_t	 Stop_Warning_Response;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_SuccessfulOutcome_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_SuccessfulOutcome;
extern asn_SEQUENCE_specifics_t asn_SPC_SBcAP_SuccessfulOutcome_specs_1;
extern asn_TYPE_member_t asn_MBR_SBcAP_SuccessfulOutcome_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SBcAP_SuccessfulOutcome_H_ */
#include <asn_internal.h>
