/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-IEs"
 * 	found in "../../src/sbcap/asn1/SBC_AP_IEs.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_Global_RAN_Node_ID_H_
#define	_SBcAP_Global_RAN_Node_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/sbcap/SBcAP_Global-GNB-ID.h>
#include <osmocom/sbcap/SBcAP_Global-NgENB-ID.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SBcAP_Global_RAN_Node_ID_PR {
	SBcAP_Global_RAN_Node_ID_PR_NOTHING,	/* No components present */
	SBcAP_Global_RAN_Node_ID_PR_global_GNB_ID,
	SBcAP_Global_RAN_Node_ID_PR_global_NgENB_ID
	/* Extensions may appear below */
	
} SBcAP_Global_RAN_Node_ID_PR;

/* SBcAP_Global-RAN-Node-ID */
typedef struct SBcAP_Global_RAN_Node_ID {
	SBcAP_Global_RAN_Node_ID_PR present;
	union SBcAP_Global_RAN_Node_ID_u {
		SBcAP_Global_GNB_ID_t	 global_GNB_ID;
		SBcAP_Global_NgENB_ID_t	 global_NgENB_ID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_Global_RAN_Node_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Global_RAN_Node_ID;
extern asn_CHOICE_specifics_t asn_SPC_SBcAP_Global_RAN_Node_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_SBcAP_Global_RAN_Node_ID_1[2];
extern asn_per_constraints_t asn_PER_type_SBcAP_Global_RAN_Node_ID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SBcAP_Global_RAN_Node_ID_H_ */
#include <asn_internal.h>
