/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-IEs"
 * 	found in "../../src/sbcap/asn1/SBC_AP_IEs.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_Number_of_Broadcasts_Requested_H_
#define	_SBcAP_Number_of_Broadcasts_Requested_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SBcAP_Number-of-Broadcasts-Requested */
typedef long	 SBcAP_Number_of_Broadcasts_Requested_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SBcAP_Number_of_Broadcasts_Requested_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_Number_of_Broadcasts_Requested;
asn_struct_free_f SBcAP_Number_of_Broadcasts_Requested_free;
asn_struct_print_f SBcAP_Number_of_Broadcasts_Requested_print;
asn_constr_check_f SBcAP_Number_of_Broadcasts_Requested_constraint;
per_type_decoder_f SBcAP_Number_of_Broadcasts_Requested_decode_aper;
per_type_encoder_f SBcAP_Number_of_Broadcasts_Requested_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SBcAP_Number_of_Broadcasts_Requested_H_ */
#include <asn_internal.h>
