/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-IEs"
 * 	found in "../../src/sbcap/asn1/SBC_AP_IEs.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_RAT_Selector_5GS_H_
#define	_SBcAP_RAT_Selector_5GS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SBcAP_RAT_Selector_5GS {
	SBcAP_RAT_Selector_5GS_true	= 0
} e_SBcAP_RAT_Selector_5GS;

/* SBcAP_RAT-Selector-5GS */
typedef long	 SBcAP_RAT_Selector_5GS_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SBcAP_RAT_Selector_5GS_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_RAT_Selector_5GS;
extern const asn_INTEGER_specifics_t asn_SPC_RAT_Selector_5GS_specs_1;
asn_struct_free_f RAT_Selector_5GS_free;
asn_struct_print_f RAT_Selector_5GS_print;
asn_constr_check_f RAT_Selector_5GS_constraint;
per_type_decoder_f RAT_Selector_5GS_decode_aper;
per_type_encoder_f RAT_Selector_5GS_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SBcAP_RAT_Selector_5GS_H_ */
#include <asn_internal.h>
