/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-IEs"
 * 	found in "../../src/sbcap/asn1/SBC_AP_IEs.asn"
 * 	`asn1c -S /home/pespin/dev/sysmocom/build/new/out/share/asn1c -fcompound-names -gen-APER -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-UPER -no-gen-example`
 */

#ifndef	_SBcAP_NgENB_ID_H_
#define	_SBcAP_NgENB_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SBcAP_NgENB_ID_PR {
	SBcAP_NgENB_ID_PR_NOTHING,	/* No components present */
	SBcAP_NgENB_ID_PR_macroNgENB_ID,
	SBcAP_NgENB_ID_PR_shortMacroNgENB_ID,
	SBcAP_NgENB_ID_PR_longMacroNgENB_ID
	/* Extensions may appear below */
	
} SBcAP_NgENB_ID_PR;

/* SBcAP_NgENB-ID */
typedef struct SBcAP_NgENB_ID {
	SBcAP_NgENB_ID_PR present;
	union SBcAP_NgENB_ID_u {
		BIT_STRING_t	 macroNgENB_ID;
		BIT_STRING_t	 shortMacroNgENB_ID;
		BIT_STRING_t	 longMacroNgENB_ID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBcAP_NgENB_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBcAP_NgENB_ID;

#ifdef __cplusplus
}
#endif

#endif	/* _SBcAP_NgENB_ID_H_ */
#include <asn_internal.h>
